# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Projects
    url: project
    weight: 10
  - name: Blog
    url: blog
    weight: 20
  - name: Publications 
    url: publication
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Mission
    url: mission
    weight: 50
  - name: Contact
    url: contact
    weight: 60