project:
  type: default
  post-render:
    - scripts/process_hugo_iframe.py

format:
  html:
    embed-resources: true 
    theme: cosmo
    sidebar: false
    navbar: false
    page-layout: custom
    code-fold: true
    include-in-header:
      text: |
        <style>
          body { padding: 0; margin: 0; overflow-x: hidden; }
        </style>